package com.jmb.survey.objects;
// Generated 14 Jan 2021, 23:35:02 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NewTable generated by hbm2java
 */
@Entity
@Table(name = "new_table", catalog = "survey")
public class NewTable implements java.io.Serializable {
	private Integer idnewTable;
	private String newTablecol;

	public NewTable() {
	}

	public NewTable(String newTablecol) {
		this.newTablecol = newTablecol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idnew_table", unique = true, nullable = false)
	public Integer getIdnewTable() {
		return this.idnewTable;
	}

	public void setIdnewTable(Integer idnewTable) {
		this.idnewTable = idnewTable;
	}

	@Column(name = "new_tablecol", length = 45)
	public String getNewTablecol() {
		return this.newTablecol;
	}

	public void setNewTablecol(String newTablecol) {
		this.newTablecol = newTablecol;
	}
}
